version: '3'

services:
  app:
    build: .
    command: /bin/ash -c "rm -f /var/www/app/tmp/pids/server.pid && rails server -b 0.0.0.0 -p 3000"
    environment:
      RAILS_ENV: development
    volumes:
      - ./:/var/www/app
    ports:
      - "3000:3000"
    tty: true